[project]
name = "nwi-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=5.2.0",
    "pandas>=2.2.0",
    "streamlit>=1.29.0"
]

[tool.poetry]
package-mode = false
